name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # Runs daily at 00:00 UTC
  workflow_dispatch:              # Allow manual triggering

permissions:
  contents: write                 # ✅ Needed to commit metrics.svg back to repo

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: header, repositories
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
